language: node_js
node_js:
  - "8"
before_script:
  - npm install
script:
  - casperjs erfan_scraper.js
  - casperjs faqeh_scraper.js
  - casperjs webteb_scraper.js
  - set API_KEY=AIzaSyDwuqhi-51gdLpnq7vfYqT71Q9wLfdw0sk
  - node gmapAPI.js
  - node gmapsReviews.js
  - npm test